version: "3.8"
services:
  postgres:
    build: .
    container_name: postgres-python-container
    environment:
      POSTGRES_USER: oalexer
      POSTGRES_PASSWORD: alexandria
      POSTGRES_DB: openalex
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    command: ["docker-entrypoint.sh", "postgres"]

  python-scripts:
    build: .
    container_name: python-scripts-container
    depends_on:
      - postgres
    volumes:
      - ./scripts:/usr/src/scripts
      - ./openalex_snapshot:/usr/src/openalex_snapshot
      - ./csv_files:/usr/src/csv_files